# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b006b75e33205230935ccbf32529f4035ec295878e08f93f5cf879ed559e7869dedac8ca722348ce9abcbc4f9774cbda6fef08a5b7874003fe8d69e3c68f67d

test:
  secret_key_base: af8835e7a4c3078f518362e05c449762867bc4df636ee11395660ebb45965d0add1d959e6054c7a0f178c6b1deb2e0d04f440d2ebc042ad94df13e89fb2660ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
